name: Build & Test dan-poll-server
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install dependencies
        working-directory: server
        run: go get ./...
      - name: Test with Go
        working-directory: server
        run: go test ./... -json > TestResults.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: server/TestResults.json
      - name: Build
        working-directory: server
        run: go build -o dan-poll-server-executable -v ./...
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: Executable
          path: server/dan-poll-server-executable